#pragma once

#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

#define GX2_SHADER_ALIGNMENT 0x100
#define GX2_SCAN_BUFFER_ALIGNMENT 0x1000
#define GX2_UNIFORM_BLOCK_ALIGNMENT 0x100
#define GX2_CONTEXT_STATE_ALIGNMENT 0x100
#define GX2_DISPLAY_LIST_ALIGNMENT 0x20
#define GX2_VERTEX_BUFFER_ALIGNMENT 0x40
#define GX2_INDEX_BUFFER_ALIGNMENT 0x20
#define GX2_DISPATCH_PARAMS_ALIGNMENT 0x100
#define GX2_DEFAULT_BUFFER_ALIGNMENT 0x40
#define GX2_STREAMOUT_BUFFER_ALIGNMENT 0x100
#define GX2_STREAMOUT_CONTEXT_ALIGNMENT 4
#define GX2_EXPORT_BUFFER_ALIGNMENT 0x100

#define GX2_FIFO_PREFERRED_SIZE (16*1024*1024)
#define GX2_FETCH_SHADER_CONTROL_FLOW_SIZE 64
#define GX2_FETCH_SHADER_INSTRUCTION_SIZE 16
#define GX2_FETCH_SHADER_ALU_INSTRUCTION_SIZE 8
#define GX2_MAX_UNIFORM_BLOCK_SIZE 65536
#define GX2_MAX_UNIFORM_BLOCK_SLOT 16
#define GX2_STREAMOUT_BUFFER_CONTEXT_SIZE 4

#define GX2_INVALID_COUNTER_VALUE_U64 0xFFFFFFFFFFFFFFFF
#define GX2_INVALID_COUNTER_VALUE_U32 0xFFFFFFFF
#define GX2_INVALID_COUNTER_VALUE_U8 0xFF
#define GX2_TOP_BOTTOM_CLOCK_CYCLES (27000000)
#define GX2_DEFAULT_GPU_TIMEOUT_IN_MILLISEC (10 * 1000)
#define GX2_DEFAULT_INTERRUPT_COUNT_LIMIT (10000)

#define GX2_MAX_VIEWPORT_SIZE        8192
#define GX2_MAX_GUARDBAND_SIZE       8192
#define GX2_MAX_TEXTURE_WIDTH        8192
#define GX2_MAX_TEXTURE_HEIGHT       8192
#define GX2_MAX_TEXTURE_DEPTH        8192
#define GX2_LOG2_MAX_TEXTURE_SIZE    13
#define GX2_MAX_TEXTURE_BUFFER_SIZE  (1 << 28)
#define GX2_CUBEMAP_FACE_COUNT  6

#define GX2_MAX_ATTRIB_BUFFERS       16
#define GX2_MAX_DRAW_VERTICES        0xFFFFFF
#define GX2_MAX_DRAW_IMMEDIATE_U32_INDICES 0x3FFE
#define GX2_MAX_PS_UNIFORM_VARS      256
#define GX2_MAX_VS_UNIFORM_VARS      256
#define GX2_MAX_UNIFORM_BLOCKS       16
#define GX2_MAX_SAMPLERS             18
#define GX2_MAX_RENDER_TARGETS       8
#define GX2_MAX_STREAMOUT_BUFFERS    4
#define GX2_MAX_COPY_SURFACE_EX_RECTS 25
#define GX2_MAX_WORK_ITEMS_PER_WORK_GROUP 64

#define GX2_UNIFORM_VAR_INVALID_OFFSET 0xFFFFFFFF
#define GX2_UNIFORM_BLOCK_INDEX_INVALID 0xFFFFFFFF
#define GX2_UNIFORM_BLOCK_INDEX_DEFAULT_BLOCK 0
#define GX2_MAX_PS_THREADS_GS_DISABLED    136
#define GX2_MAX_PS_THREADS_GS_ENABLED     124
#define GX2_MAX_VS_THREADS_GS_DISABLED     48
#define GX2_MAX_VS_THREADS_GS_ENABLED      32
#define GX2_MAX_GS_THREADS                  8
#define GX2_TOTAL_GPRS_GS_DISABLED  248
#define GX2_TOTAL_GPRS_GS_ENABLED  184
#define GX2_TOTAL_STACK_ENTRIES 256
#define GX2_SYSTEM_GENERATED_ATTRIBUTE  GX2_MAX_ATTRIB_BUFFERS
#define GX2_SYSGEN_ATTRIB_TESSELLATION_BARYC 0
#define GX2_SYSGEN_ATTRIB_TESSELLATION_INDEX 1

#define GX2_MAX_TEXTURE_ANISOTROPY 16.f
#define GX2_AUX_BUFFER_CLEAR_VALUE 0xCC

#define GX2_NUM_COUNTER_CP          0x01
#define GX2_NUM_COUNTER_GRBM        0x02
#define GX2_NUM_COUNTER_PA_SU       0x04
#define GX2_NUM_COUNTER_PA_SC       0x04
#define GX2_NUM_COUNTER_VGT         0x04
#define GX2_NUM_COUNTER_SQ          0x04
#define GX2_NUM_COUNTER_SPI         0x04
#define GX2_NUM_COUNTER_SX          0x04
#define GX2_NUM_COUNTER_SMX         0x04
#define GX2_NUM_COUNTER_TD          0x01
#define GX2_NUM_COUNTER_TA          0x02
#define GX2_NUM_COUNTER_TCP         0x04
#define GX2_NUM_COUNTER_TCC         0x04
#define GX2_NUM_COUNTER_CB          0x04
#define GX2_NUM_COUNTER_DB          0x04
#define GX2_NUM_COUNTER_PIPELINE    0x08

#define GX2_PIPELINE_COUNTERS_PSINVO_OFFSET  0
#define GX2_PIPELINE_COUNTERS_CPRIM_OFFSET   1
#define GX2_PIPELINE_COUNTERS_CINVO_OFFSET   2
#define GX2_PIPELINE_COUNTERS_VSINVO_OFFSET  3
#define GX2_PIPELINE_COUNTERS_GSINVO_OFFSET  4
#define GX2_PIPELINE_COUNTERS_GSPRIM_OFFSET  5
#define GX2_PIPELINE_COUNTERS_IAPRIM_OFFSET  6
#define GX2_PIPELINE_COUNTERS_IAVERT_OFFSET  7

#ifdef __cplusplus
}
#endif // __cplusplus
